package BP.WF.CloudWS;

import BP.WF.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


	// CODEGEN: 参数"bytes"需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为"System.Xml.Serialization.XmlElementAttribute"。









	// CODEGEN: 参数"GetFlowXMLResult"需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为"System.Xml.Serialization.XmlElementAttribute"。


	// CODEGEN: 参数"bytes"需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为"System.Xml.Serialization.XmlElementAttribute"。


	// CODEGEN: 参数"GetImageBytesByNoResult"需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为"System.Xml.Serialization.XmlElementAttribute"。

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Diagnostics.DebuggerStepThroughAttribute()][System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")][System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)][System.ServiceModel.MessageContractAttribute(WrapperName="SavePriFlowTemplete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)] public partial class SavePriFlowTempleteRequest
public class SavePriFlowTempleteRequest
{

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)] public string dir;
	public String dir;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)] public string flowName;
	public String flowName;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)][System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] public byte[] bytes;
//C# TO JAVA CONVERTER WARNING: Unsigned integer types have no direct equivalent in Java:
//ORIGINAL LINE: [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)][System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] public byte[] bytes;
	public byte[] bytes;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)] public string userNo;
	public String userNo;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)] public string nodeNames;
	public String nodeNames;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)] public int nodesCount;
	public int nodesCount;

	public SavePriFlowTempleteRequest()
	{
	}

//C# TO JAVA CONVERTER WARNING: Unsigned integer types have no direct equivalent in Java:
//ORIGINAL LINE: public SavePriFlowTempleteRequest(string dir, string flowName, byte[] bytes, string userNo, string nodeNames, int nodesCount)
	public SavePriFlowTempleteRequest(String dir, String flowName, byte[] bytes, String userNo, String nodeNames, int nodesCount)
	{
		this.dir = dir;
		this.flowName = flowName;
		this.bytes = bytes;
		this.userNo = userNo;
		this.nodeNames = nodeNames;
		this.nodesCount = nodesCount;
	}
}