package BP.WF.CloudWS;

import BP.WF.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Diagnostics.DebuggerStepThroughAttribute()][System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")] public partial class WSSoapClient: System.ServiceModel.ClientBase<BP.WF.CloudWS.WSSoap>, BP.WF.CloudWS.WSSoap
public class WSSoapClient extends System.ServiceModel.ClientBase<BP.WF.CloudWS.WSSoap> implements BP.WF.CloudWS.WSSoap
{

	public WSSoapClient()
	{
	}

	public WSSoapClient(String endpointConfigurationName)
	{
		super(endpointConfigurationName);
	}

	public WSSoapClient(String endpointConfigurationName, String remoteAddress)
	{
		super(endpointConfigurationName, remoteAddress);
	}

	public WSSoapClient(String endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
	{
		super(endpointConfigurationName, remoteAddress);
	}

	public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
	{
		super(binding, remoteAddress);
	}

	public final boolean GetNetState()
	{
		return super.getChannel().GetNetState();
	}

	public final boolean AddPriFormDir(String userNo, String pwd, String guid, String parentNo, String dirName)
	{
		return super.getChannel().AddPriFormDir(userNo, pwd, guid, parentNo, dirName);
	}

	public final boolean DeletePriFormDir(String userNo, String pwd, String guid, String no)
	{
		return super.getChannel().DeletePriFormDir(userNo, pwd, guid, no);
	}

	public final boolean EditPriFormDir(String userNo, String pwd, String guid, String no, String dirName)
	{
		return super.getChannel().EditPriFormDir(userNo, pwd, guid, no, dirName);
	}

	public final System.Data.DataTable GetFormPagingData(boolean isPublic, String searchText, int pageIdx, int pageSize, String dirStr, String userNo)
	{
		return super.getChannel().GetFormPagingData(isPublic, searchText, pageIdx, pageSize, dirStr, userNo);
	}

	public final int GetFormTotalCount(boolean isPublic, String searchText, String dirStr, String userNo)
	{
		return super.getChannel().GetFormTotalCount(isPublic, searchText, dirStr, userNo);
	}

	public final System.Data.DataTable PriFormDir(String userNo, String pwd, String guid)
	{
		return super.getChannel().PriFormDir(userNo, pwd, guid);
	}

	public final System.Data.DataTable GetRecentlyPriFormTemp(String userNo, String pwd, String guid)
	{
		return super.getChannel().GetRecentlyPriFormTemp(userNo, pwd, guid);
	}

	public final String SavePubFormToPri(String userNo, String pwd, String guid, String dir, String no)
	{
		return super.getChannel().SavePubFormToPri(userNo, pwd, guid, dir, no);
	}

	public final System.Data.DataTable GetPubFormTree()
	{
		return super.getChannel().GetPubFormTree();
	}

	public final System.Data.DataTable GetRecentlyFormTemp()
	{
		return super.getChannel().GetRecentlyFormTemp();
	}

	public final Object[] GetFormData(boolean isPublic, String guid)
	{
		return super.getChannel().GetFormData(isPublic, guid);
	}

	public final String SavePubToPri(String userNo, String pwd, String guid, String dir, String no)
	{
		return super.getChannel().SavePubToPri(userNo, pwd, guid, dir, no);
	}

	public final String PriLogin(String userNo, String password)
	{
		return super.getChannel().PriLogin(userNo, password);
	}

	public final String IsExitUser(String userNo)
	{
		return super.getChannel().IsExitUser(userNo);
	}

	public final String PriRegUser(String userNo, String userName, String password, String email, String tel, String qq, int userType, int userTarget)
	{
		return super.getChannel().PriRegUser(userNo, userName, password, email, tel, qq, userType, userTarget);
	}

	public final System.Data.DataTable PriFlowDir(String userNo, String pwd, String guid)
	{
		return super.getChannel().PriFlowDir(userNo, pwd, guid);
	}

	public final boolean AddPriFlowDir(String userNo, String pwd, String guid, String parentNo, String dirName)
	{
		return super.getChannel().AddPriFlowDir(userNo, pwd, guid, parentNo, dirName);
	}

	public final boolean DeletePriFlowDir(String userNo, String pwd, String guid, String no)
	{
		return super.getChannel().DeletePriFlowDir(userNo, pwd, guid, no);
	}

	public final boolean EditPriFlowDir(String userNo, String pwd, String guid, String no, String dirName)
	{
		return super.getChannel().EditPriFlowDir(userNo, pwd, guid, no, dirName);
	}

	public final System.Data.DataTable GetRecentlyPriFlowTemp(String userNo, String pwd, String guid)
	{
		return super.getChannel().GetRecentlyPriFlowTemp(userNo, pwd, guid);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] BP.WF.CloudWS.SavePriFlowTempleteResponse BP.WF.CloudWS.WSSoap.SavePriFlowTemplete(BP.WF.CloudWS.SavePriFlowTempleteRequest request)
	public final BP.WF.CloudWS.SavePriFlowTempleteResponse SavePriFlowTemplete(BP.WF.CloudWS.SavePriFlowTempleteRequest request)
	{
		return super.getChannel().SavePriFlowTemplete(request);
	}

//C# TO JAVA CONVERTER WARNING: Unsigned integer types have no direct equivalent in Java:
//ORIGINAL LINE: public bool SavePriFlowTemplete(string dir, string flowName, byte[] bytes, string userNo, string nodeNames, int nodesCount)
	public final boolean SavePriFlowTemplete(String dir, String flowName, byte[] bytes, String userNo, String nodeNames, int nodesCount)
	{
		BP.WF.CloudWS.SavePriFlowTempleteRequest inValue = new BP.WF.CloudWS.SavePriFlowTempleteRequest();
		inValue.dir = dir;
		inValue.flowName = flowName;
		inValue.bytes = bytes;
		inValue.userNo = userNo;
		inValue.nodeNames = nodeNames;
		inValue.nodesCount = nodesCount;
		BP.WF.CloudWS.SavePriFlowTempleteResponse retVal = ((BP.WF.CloudWS.WSSoap)(this)).SavePriFlowTemplete(inValue);
		return retVal.SavePriFlowTempleteResult;
	}

	public final System.Data.DataTable GetPriFlowTemplateByGuid(String guid)
	{
		return super.getChannel().GetPriFlowTemplateByGuid(guid);
	}

	public final System.Data.DataTable GetPubFlowTree()
	{
		return super.getChannel().GetPubFlowTree();
	}

	public final System.Data.DataTable GetDataByNo(String no)
	{
		return super.getChannel().GetDataByNo(no);
	}

	public final System.Data.DataTable GetSonDirByParentNo(String no)
	{
		return super.getChannel().GetSonDirByParentNo(no);
	}

	public final System.Data.DataTable GetRecentlyFlowTemp()
	{
		return super.getChannel().GetRecentlyFlowTemp();
	}

	public final int GetTotalCount(boolean isPublic, String searchText, String dirStr, String userNo)
	{
		return super.getChannel().GetTotalCount(isPublic, searchText, dirStr, userNo);
	}

	public final System.Data.DataTable GetPagingData(boolean isPublic, String searchText, int pageIdx, int pageSize, String dirStr, String userNo)
	{
		return super.getChannel().GetPagingData(isPublic, searchText, pageIdx, pageSize, dirStr, userNo);
	}

	public final System.Data.DataTable GetFlowTemplateByGuid(String guid)
	{
		return super.getChannel().GetFlowTemplateByGuid(guid);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] BP.WF.CloudWS.GetFlowXMLResponse BP.WF.CloudWS.WSSoap.GetFlowXML(BP.WF.CloudWS.GetFlowXMLRequest request)
	public final BP.WF.CloudWS.GetFlowXMLResponse GetFlowXML(BP.WF.CloudWS.GetFlowXMLRequest request)
	{
		return super.getChannel().GetFlowXML(request);
	}

//C# TO JAVA CONVERTER WARNING: Unsigned integer types have no direct equivalent in Java:
//ORIGINAL LINE: public byte[] GetFlowXML(bool isPublic, string guid)
	public final byte[] GetFlowXML(boolean isPublic, String guid)
	{
		BP.WF.CloudWS.GetFlowXMLRequest inValue = new BP.WF.CloudWS.GetFlowXMLRequest();
		inValue.isPublic = isPublic;
		inValue.guid = guid;
		BP.WF.CloudWS.GetFlowXMLResponse retVal = ((BP.WF.CloudWS.WSSoap)(this)).GetFlowXML(inValue);
		return retVal.GetFlowXMLResult;
	}

	public final System.Data.DataTable GetCloudFlowsDDlTreeDt()
	{
		return super.getChannel().GetCloudFlowsDDlTreeDt();
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] BP.WF.CloudWS.SaveToFlowTempleteResponse BP.WF.CloudWS.WSSoap.SaveToFlowTemplete(BP.WF.CloudWS.SaveToFlowTempleteRequest request)
	public final BP.WF.CloudWS.SaveToFlowTempleteResponse SaveToFlowTemplete(BP.WF.CloudWS.SaveToFlowTempleteRequest request)
	{
		return super.getChannel().SaveToFlowTemplete(request);
	}

//C# TO JAVA CONVERTER WARNING: Unsigned integer types have no direct equivalent in Java:
//ORIGINAL LINE: public bool SaveToFlowTemplete(string no, string flowName, byte[] bytes, string sharer, string nodeNames, int nodesCount)
	public final boolean SaveToFlowTemplete(String no, String flowName, byte[] bytes, String sharer, String nodeNames, int nodesCount)
	{
		BP.WF.CloudWS.SaveToFlowTempleteRequest inValue = new BP.WF.CloudWS.SaveToFlowTempleteRequest();
		inValue.no = no;
		inValue.flowName = flowName;
		inValue.bytes = bytes;
		inValue.sharer = sharer;
		inValue.nodeNames = nodeNames;
		inValue.nodesCount = nodesCount;
		BP.WF.CloudWS.SaveToFlowTempleteResponse retVal = ((BP.WF.CloudWS.WSSoap)(this)).SaveToFlowTemplete(inValue);
		return retVal.SaveToFlowTempleteResult;
	}

	public final System.Data.DataTable GetFlowTemFromCloud(String str)
	{
		return super.getChannel().GetFlowTemFromCloud(str);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] BP.WF.CloudWS.GetImageBytesByNoResponse BP.WF.CloudWS.WSSoap.GetImageBytesByNo(BP.WF.CloudWS.GetImageBytesByNoRequest request)
	public final BP.WF.CloudWS.GetImageBytesByNoResponse GetImageBytesByNo(BP.WF.CloudWS.GetImageBytesByNoRequest request)
	{
		return super.getChannel().GetImageBytesByNo(request);
	}

//C# TO JAVA CONVERTER WARNING: Unsigned integer types have no direct equivalent in Java:
//ORIGINAL LINE: public byte[] GetImageBytesByNo(string no)
	public final byte[] GetImageBytesByNo(String no)
	{
		BP.WF.CloudWS.GetImageBytesByNoRequest inValue = new BP.WF.CloudWS.GetImageBytesByNoRequest();
		inValue.no = no;
		BP.WF.CloudWS.GetImageBytesByNoResponse retVal = ((BP.WF.CloudWS.WSSoap)(this)).GetImageBytesByNo(inValue);
		return retVal.GetImageBytesByNoResult;
	}
}