package BP.WF.CloudWS;

import BP.WF.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------




//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")][System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudWS.WSSoap")] public interface WSSoap
public interface WSSoap
{

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNetState", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] bool GetNetState();
	boolean GetNetState();

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPriFormDir", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] bool AddPriFormDir(string userNo, string pwd, string guid, string parentNo, string dirName);
	boolean AddPriFormDir(String userNo, String pwd, String guid, String parentNo, String dirName);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePriFormDir", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] bool DeletePriFormDir(string userNo, string pwd, string guid, string no);
	boolean DeletePriFormDir(String userNo, String pwd, String guid, String no);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditPriFormDir", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] bool EditPriFormDir(string userNo, string pwd, string guid, string no, string dirName);
	boolean EditPriFormDir(String userNo, String pwd, String guid, String no, String dirName);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFormPagingData", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] System.Data.DataTable GetFormPagingData(bool isPublic, string searchText, int pageIdx, int pageSize, string dirStr, string userNo);
	System.Data.DataTable GetFormPagingData(boolean isPublic, String searchText, int pageIdx, int pageSize, String dirStr, String userNo);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFormTotalCount", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] int GetFormTotalCount(bool isPublic, string searchText, string dirStr, string userNo);
	int GetFormTotalCount(boolean isPublic, String searchText, String dirStr, String userNo);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PriFormDir", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] System.Data.DataTable PriFormDir(string userNo, string pwd, string guid);
	System.Data.DataTable PriFormDir(String userNo, String pwd, String guid);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentlyPriFormTemp", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] System.Data.DataTable GetRecentlyPriFormTemp(string userNo, string pwd, string guid);
	System.Data.DataTable GetRecentlyPriFormTemp(String userNo, String pwd, String guid);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePubFormToPri", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] string SavePubFormToPri(string userNo, string pwd, string guid, string dir, string no);
	String SavePubFormToPri(String userNo, String pwd, String guid, String dir, String no);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPubFormTree", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] System.Data.DataTable GetPubFormTree();
	System.Data.DataTable GetPubFormTree();

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentlyFormTemp", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)] System.Data.DataTable GetRecentlyFormTemp();
	System.Data.DataTable GetRecentlyFormTemp();

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFormData", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] object[] GetFormData(bool isPublic, string guid);
	Object[] GetFormData(boolean isPublic, String guid);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePubToPri", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] string SavePubToPri(string userNo, string pwd, string guid, string dir, string no);
	String SavePubToPri(String userNo, String pwd, String guid, String dir, String no);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PriLogin", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] string PriLogin(string userNo, string password);
	String PriLogin(String userNo, String password);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsExitUser", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] string IsExitUser(string userNo);
	String IsExitUser(String userNo);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PriRegUser", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] string PriRegUser(string userNo, string userName, string password, string email, string tel, string qq, int userType, int userTarget);
	String PriRegUser(String userNo, String userName, String password, String email, String tel, String qq, int userType, int userTarget);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PriFlowDir", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable PriFlowDir(string userNo, string pwd, string guid);
	System.Data.DataTable PriFlowDir(String userNo, String pwd, String guid);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPriFlowDir", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] bool AddPriFlowDir(string userNo, string pwd, string guid, string parentNo, string dirName);
	boolean AddPriFlowDir(String userNo, String pwd, String guid, String parentNo, String dirName);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePriFlowDir", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] bool DeletePriFlowDir(string userNo, string pwd, string guid, string no);
	boolean DeletePriFlowDir(String userNo, String pwd, String guid, String no);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditPriFlowDir", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] bool EditPriFlowDir(string userNo, string pwd, string guid, string no, string dirName);
	boolean EditPriFlowDir(String userNo, String pwd, String guid, String no, String dirName);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentlyPriFlowTemp", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetRecentlyPriFlowTemp(string userNo, string pwd, string guid);
	System.Data.DataTable GetRecentlyPriFlowTemp(String userNo, String pwd, String guid);

	// CODEGEN: 参数"bytes"需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为"System.Xml.Serialization.XmlElementAttribute"。
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePriFlowTemplete", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] BP.WF.CloudWS.SavePriFlowTempleteResponse SavePriFlowTemplete(BP.WF.CloudWS.SavePriFlowTempleteRequest request);
	BP.WF.CloudWS.SavePriFlowTempleteResponse SavePriFlowTemplete(BP.WF.CloudWS.SavePriFlowTempleteRequest request);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPriFlowTemplateByGuid", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetPriFlowTemplateByGuid(string guid);
	System.Data.DataTable GetPriFlowTemplateByGuid(String guid);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPubFlowTree", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetPubFlowTree();
	System.Data.DataTable GetPubFlowTree();

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataByNo", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetDataByNo(string no);
	System.Data.DataTable GetDataByNo(String no);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSonDirByParentNo", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetSonDirByParentNo(string no);
	System.Data.DataTable GetSonDirByParentNo(String no);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentlyFlowTemp", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetRecentlyFlowTemp();
	System.Data.DataTable GetRecentlyFlowTemp();

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalCount", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] int GetTotalCount(bool isPublic, string searchText, string dirStr, string userNo);
	int GetTotalCount(boolean isPublic, String searchText, String dirStr, String userNo);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPagingData", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetPagingData(bool isPublic, string searchText, int pageIdx, int pageSize, string dirStr, string userNo);
	System.Data.DataTable GetPagingData(boolean isPublic, String searchText, int pageIdx, int pageSize, String dirStr, String userNo);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowTemplateByGuid", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetFlowTemplateByGuid(string guid);
	System.Data.DataTable GetFlowTemplateByGuid(String guid);

	// CODEGEN: 参数"GetFlowXMLResult"需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为"System.Xml.Serialization.XmlElementAttribute"。
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowXML", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] BP.WF.CloudWS.GetFlowXMLResponse GetFlowXML(BP.WF.CloudWS.GetFlowXMLRequest request);
	BP.WF.CloudWS.GetFlowXMLResponse GetFlowXML(BP.WF.CloudWS.GetFlowXMLRequest request);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCloudFlowsDDlTreeDt", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetCloudFlowsDDlTreeDt();
	System.Data.DataTable GetCloudFlowsDDlTreeDt();

	// CODEGEN: 参数"bytes"需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为"System.Xml.Serialization.XmlElementAttribute"。
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveToFlowTemplete", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] BP.WF.CloudWS.SaveToFlowTempleteResponse SaveToFlowTemplete(BP.WF.CloudWS.SaveToFlowTempleteRequest request);
	BP.WF.CloudWS.SaveToFlowTempleteResponse SaveToFlowTemplete(BP.WF.CloudWS.SaveToFlowTempleteRequest request);

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowTemFromCloud", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] System.Data.DataTable GetFlowTemFromCloud(string str);
	System.Data.DataTable GetFlowTemFromCloud(String str);

	// CODEGEN: 参数"GetImageBytesByNoResult"需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为"System.Xml.Serialization.XmlElementAttribute"。
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImageBytesByNo", ReplyAction="*")][System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)][System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))] BP.WF.CloudWS.GetImageBytesByNoResponse GetImageBytesByNo(BP.WF.CloudWS.GetImageBytesByNoRequest request);
	BP.WF.CloudWS.GetImageBytesByNoResponse GetImageBytesByNo(BP.WF.CloudWS.GetImageBytesByNoRequest request);
}