package BP.Sys;

import BP.En.*;
import java.util.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由 代码生成器 自动生成。
//
//     可以对此文件进行更改。为避免无意中覆盖更改，请在更改此文件后删除本行并标注为"请勿覆盖"。
// </auto-generated>
//------------------------------------------------------------------------------


/** 
 Excel字段字段常量
*/
public class ExcelFieldAttr extends EntityNoNameAttr
{
	/** 
	 单元格名称
	*/
	public static final String CellName = "CellName";

	/** 
	 行号
	*/
	public static final String CellRow = "CellRow";

	/** 
	 列号
	*/
	public static final String CellColumn = "CellColumn";

	/** 
	 ExcelSheet
	*/
	public static final String FK_ExcelSheet = "FK_ExcelSheet";

	/** 
	 存储字段名
	*/
	public static final String Field = "Field";

	/** 
	 存储数据表
	*/
	public static final String FK_ExcelTable = "FK_ExcelTable";

	/** 
	 值类型
	*/
	public static final String DataType = "DataType";

	/** 
	 数据源表/枚举
	*/
	public static final String UIBindKey = "UIBindKey";

	/** 
	 数据源表No
	*/
	public static final String UIRefKey = "UIRefKey";

	/** 
	 数据源表Name
	*/
	public static final String UIRefKeyText = "UIRefKeyText";

	/** 
	 校验器
	*/
	public static final String Validators = "Validators";

	/** 
	 Excel模板
	*/
	public static final String FK_ExcelFile = "FK_ExcelFile";

	/** 
	  AtPara
	*/
	public static final String AtPara = "AtPara";

	/** 
	 单元格确认方式
	*/
	public static final String ConfirmKind = "ConfirmKind";

	/** 
	 单元格确认方向移动量
	*/
	public static final String ConfirmCellCount = "ConfirmCellCount";

	/** 
	 对应单元格值
	*/
	public static final String ConfirmCellValue = "ConfirmCellValue";

	/** 
	 对应单元格值重复选定次序
	*/
	public static final String ConfirmRepeatIndex = "ConfirmRepeatIndex";

	/** 
	 不计非空
	*/
	public static final String SkipIsNull = "SkipIsNull";

	/** 
	 同步到字段
	*/
	public static final String SyncToField = "SyncToField";
}