package BP.Sys;

import BP.En.*;
import java.util.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由 代码生成器 自动生成。
//
//     可以对此文件进行更改。为避免无意中覆盖更改，请在更改此文件后删除本行并标注为"请勿覆盖"。
// </auto-generated>
//------------------------------------------------------------------------------


/** 
 ExcelSheet字段常量
*/
public class ExcelSheetAttr extends EntityNoNameAttr
{
	/** 
	 Excel模板
	*/
	public static final String FK_ExcelFile = "FK_ExcelFile";

	/** 
	 Sheet索引
	*/
	public static final String SheetIndex = "SheetIndex";

}